/* EXERCICIOS LIVRARIA */

CREATE DATABASE LIVRARIA;

CREATE TABLE LIVROS(
	NM_LIVRO VARCHAR(100),
	NM_AUTOR VARCHAR(100),
	SEXO_AUTOR CHAR(10),
	PAGINAS INT(5),
	NM_EDITORA VARCHAR(50),
	VALOR_LIVRO FLOAT(10,2),
	UF_EDITORA CHAR(2),
	ANO_PUBLI INT(4)
);

/* INSERT */

INSERT INTO LIVROS(NM_LIVRO,NM_AUTOR,SEXO_AUTOR,PAGINAS,NM_EDITORA,VALOR_LIVRO,UF_EDITORA,ANO_PUBLI) 
VALUES('Cavaleiro Real', 'Ana Claudia', 'Feminino', 465, 'Atlas', 49.9, 'RJ', 2009);

INSERT INTO LIVROS(NM_LIVRO,NM_AUTOR,SEXO_AUTOR,PAGINAS,NM_EDITORA,VALOR_LIVRO,UF_EDITORA,ANO_PUBLI) 
VALUES('SQL para Leigos', 'João Nunes', 'Masculino', 450, 'Addison', 98, 'SP', 2018);

INSERT INTO LIVROS(NM_LIVRO,NM_AUTOR,SEXO_AUTOR,PAGINAS,NM_EDITORA,VALOR_LIVRO,UF_EDITORA,ANO_PUBLI) 
VALUES('Receitas Caseiras', 'Celia Tavares', 'Feminino', 210, 'Atlas', 45, 'RJ', 2008);

INSERT INTO LIVROS(NM_LIVRO,NM_AUTOR,SEXO_AUTOR,PAGINAS,NM_EDITORA,VALOR_LIVRO,UF_EDITORA,ANO_PUBLI) 
VALUES('Pessoas Efetivas', 'Eduardo Santos', 'Masculino', 390, 'Beta', 78.99, 'RJ', 2018);

INSERT INTO LIVROS(NM_LIVRO,NM_AUTOR,SEXO_AUTOR,PAGINAS,NM_EDITORA,VALOR_LIVRO,UF_EDITORA,ANO_PUBLI) 
VALUES('Habitos Saudáveis', 'Eduardo Santos', 'Masculino', 630, 'Beta', 150.98, 'RJ', 2019);

INSERT INTO LIVROS(NM_LIVRO,NM_AUTOR,SEXO_AUTOR,PAGINAS,NM_EDITORA,VALOR_LIVRO,UF_EDITORA,ANO_PUBLI) 
VALUES('A Casa Marrom', 'Hermes Macedo', 'Masculino', 250, 'Bubba', 60, 'MG', 2016);

INSERT INTO LIVROS(NM_LIVRO,NM_AUTOR,SEXO_AUTOR,PAGINAS,NM_EDITORA,VALOR_LIVRO,UF_EDITORA,ANO_PUBLI) 
VALUES('Estacio Querido', 'Geraldo Francisco', 'Masculino', 310, 'Insignia', 100, 'ES', 2015);

INSERT INTO LIVROS(NM_LIVRO,NM_AUTOR,SEXO_AUTOR,PAGINAS,NM_EDITORA,VALOR_LIVRO,UF_EDITORA,ANO_PUBLI) 
VALUES('Pra sempre amigas', 'Leda Silva', 'Feminino', 510, 'Insignia', 78.98, 'ES', 2011);

INSERT INTO LIVROS(NM_LIVRO,NM_AUTOR,SEXO_AUTOR,PAGINAS,NM_EDITORA,VALOR_LIVRO,UF_EDITORA,ANO_PUBLI) 
VALUES('Copas Inesqueciveis', 'Marco Alcantara', 'Masculino', 200, 'Larson', 130.98, 'RS', 2018);

INSERT INTO LIVROS(NM_LIVRO,NM_AUTOR,SEXO_AUTOR,PAGINAS,NM_EDITORA,VALOR_LIVRO,UF_EDITORA,ANO_PUBLI) 
VALUES('O poder da mente', 'Clara Mafra', 'Feminino', 120, 'Continental', 56.58, 'SP', 2017);

/* 1ª QUERIE */

SELECT 
	NM_LIVRO AS 'Nome do Livro',
	NM_AUTOR AS 'Nome do Autor',
	SEXO_AUTOR AS 'Sexo do Autor',
	PAGINAS AS 'Numero de Páginas',
	NM_EDITORA AS 'Nome da Editora',
	VALOR_LIVRO AS 'Valor do Livro',
	UF_EDITORA AS 'UF da Editora',
	ANO_PUBLI AS 'Ano da Publicacao'
FROM LIVROS;

/* 2ª QUERIE */

SELECT 
	NM_LIVRO AS 'Nome do Livro',
	NM_EDITORA AS 'Nome da Editora'
FROM LIVROS;

/* 3ª QUERIE */

SELECT 
	NM_LIVRO AS 'Nome do Livro',
	UF_EDITORA AS 'UF da Editora'
FROM LIVROS WHERE SEXO_AUTOR = 'Masculino';
	
/* 4ª QUERIE */

SELECT 
	NM_LIVRO AS 'Nome do Livro',
	PAGINAS AS 'Numero de Páginas'
FROM LIVROS WHERE 
	SEXO_AUTOR = 'Feminino';
	
/* 5ª QUERIE */

SELECT
	UF_EDITORA AS 'UF da Editora',
	NM_LIVRO AS 'Nome do Livro',
	VALOR_LIVRO AS 'Valor do Livro'
FROM LIVROS WHERE 
	UF_EDITORA = 'SP';
	
/* 6ª QUERIE */

SELECT 
	NM_LIVRO AS 'Nome do Livro',
	NM_AUTOR AS 'Nome do Autor',
	SEXO_AUTOR AS 'Sexo do Autor',
	PAGINAS AS 'Numero de Páginas',
	NM_EDITORA AS 'Nome da Editora',
	VALOR_LIVRO AS 'Valor do Livro',
	UF_EDITORA AS 'UF da Editora',
	ANO_PUBLI AS 'Ano da Publicacao'
FROM LIVROS WHERE 
	SEXO_AUTOR = 'Masculino' AND (UF_EDITORA = 'SP' OR UF_EDITORA = 'RJ');
	